import { documentLayout } from "./layouts.mjs";
import { services, getService } from "./data/services.mjs";
import { projects, getProject } from "./data/projects.mjs";
import { site } from "./data/site.mjs";
import { pageHero, serviceHero, caseHero, globalCTA, partnerWall, projectCard, serviceCard, relatedProjects, relatedServices } from "./components.mjs";

const sectionHead = (kicker, title, copy = "") => `<div class="section-head"><div><div class="kicker">${kicker}</div><h2 class="section-title">${title}</h2></div>${copy ? `<p class="section-copy">${copy}</p>` : ""}</div>`;


export function aboutPage() {
  const hero = pageHero({
    kicker: "About Grenada",
    title: `Built around how <em>real estate moves.</em>`,
    summary: "Grenada Studio combines digital expertise, field execution and modern production capabilities for real estate projects and major auctions across Egypt and Saudi Arabia.",
    breadcrumbItems: [{ label: "About", href: "/about/" }],
    visual: `<div class="page-media-frame"><img src="/assets/photos/strategy.webp" srcset="/assets/photos/strategy-m.webp 960w, /assets/photos/strategy.webp 2200w" sizes="(max-width: 820px) 100vw, 50vw" alt="Campaign strategy session in a creative studio" width="2200" height="1467" fetchpriority="high"><span>Inside Grenada / 2026</span></div>`,
    modifier: "about-hero"
  });
  const story = `<section class="section template-story"><div class="shell"><div class="editorial-grid"><div class="editorial-index kicker" data-reveal>More than a decade</div><div class="editorial-copy" data-reveal><h2>One team between the market story and the market response.</h2><p>Grenada follows market shifts closely, then translates them into sharper positioning, stronger creative and measurable execution. The studio’s work spans digital campaigns, physical touchpoints, production and live auction environments — disciplines that are usually split between different suppliers.</p><p>The model is intentionally integrated: strategy can shape creative, creative can shape media, and on-ground execution can feed back into the campaign without a handoff gap.</p></div></div></div></section>`;
  const values = `<section class="section"><div class="shell">${sectionHead("What guides us", "Principles that show up in the work.", "The values in Grenada’s profile are treated as operating principles rather than decorative statements.")}<div class="values"><article class="value" data-reveal><span class="num">01</span><div><h3>Innovation</h3><p>Use current tools, channels and production methods when they create a better market outcome.</p></div></article><article class="value" data-reveal><span class="num">02</span><div><h3>Commitment</h3><p>Stay close to the project from positioning through execution, reporting and refinement.</p></div></article><article class="value" data-reveal><span class="num">03</span><div><h3>Flexibility</h3><p>Adapt the campaign system to the asset, audience, sales environment and launch conditions.</p></div></article></div></div></section>`;
  const partners = partnerWall({ headingId: "about-partners-title" });
  return documentLayout({ title: "About", description: "About Grenada Studio — an integrated real estate marketing and creative agency connecting strategy, digital execution, production and field campaigns.", active: "about", path: "/about/", content: hero + story + values + partners + globalCTA() });
}

export function servicesIndexPage() {
  const hero = pageHero({ kicker: "Capabilities / 01—10", title: "One partner. <em>Full-market execution.</em>", summary: "From the first brand idea to launch day, performance tracking and on-ground coverage, Grenada connects the disciplines real estate projects usually split across multiple suppliers.", breadcrumbItems: [{ label: "Services", href: "/services/" }], modifier: "services-index-hero" });
  const list = `<section class="section"><div class="shell">${sectionHead("Services", "10 capabilities. One operating system.", "Each capability has its own detail page, while the shared template controls the header, structure, related work and CTA across all service pages.")}<div class="template-service-grid template-service-grid--index">${services.map(serviceCard).join("")}</div></div></section>`;
  const integration = `<section class="template-statement"><div class="shell"><div class="statement-grid"><div class="kicker" data-reveal>Integrated by design</div><h2 data-reveal>Use one capability. Or connect the whole <em>launch system.</em></h2><p data-reveal>Branding, content, web, media, production and field execution can be commissioned separately, but the strongest advantage comes when they share one positioning and measurement framework.</p></div></div></section>`;
  return documentLayout({ title: "Services", description: "Grenada Studio services: social media, content, branding, design, motion, web development, SEO, paid media, performance marketing and media production.", active: "services", path: "/services/", content: hero + list + integration + globalCTA({ kicker: "Build the right scope", title: "Choose the capabilities your <em>project needs.</em>", text: "Start with one discipline or build an integrated launch team around the asset.", button: "Discuss your project" }) });
}

export function servicePage(slug) {
  const service = getService(slug);
  if (!service) return null;
  const related = service.relatedProjects.map(getProject).filter(Boolean);
  const connected = services.filter((item) => item.slug !== service.slug && related.some((p) => p.serviceSlugs.includes(item.slug))).slice(0, 3);
  const intro = `<section class="section service-overview"><div class="shell"><div class="editorial-grid"><div class="editorial-index kicker" data-reveal>What it does</div><div class="editorial-copy" data-reveal><h2>${service.intro}</h2></div></div></div></section>`;
  const capabilities = `<section class="section service-capabilities"><div class="shell">${sectionHead("Scope", "What this capability can include.", "The exact scope is shaped around the project, campaign stage and commercial objective.")}<div class="capability-grid">${service.capabilities.map((item, i) => `<article class="capability-item" data-reveal><span>${String(i + 1).padStart(2, "0")}</span><h3>${item}</h3></article>`).join("")}</div></div></section>`;
  const approach = `<section class="section service-method"><div class="shell">${sectionHead("Working model", "Strategy to execution, without the handoff gap.", "The capability plugs into the same Grenada process used across integrated projects.")}<div class="process"><article class="step" data-reveal><span>01 / POSITION</span><div><h3>Define what must move.</h3><p>Clarify the audience, offer, context and role this capability plays in the wider project.</p></div></article><article class="step" data-reveal><span>02 / BUILD</span><div><h3>Create the system.</h3><p>Develop the assets, structure and production requirements needed for consistent execution.</p></div></article><article class="step" data-reveal><span>03 / ACTIVATE</span><div><h3>Put it in market.</h3><p>Connect the work to the relevant channels, launch plan, field touchpoints or sales journey.</p></div></article><article class="step" data-reveal><span>04 / REFINE</span><div><h3>Improve from evidence.</h3><p>Use reporting, campaign signals and stakeholder feedback to sharpen the next iteration.</p></div></article></div></div></section>`;
  return documentLayout({ title: service.title, description: service.summary, active: "services", path: `/services/${service.slug}/`, bodyClass: "service-page", content: serviceHero(service) + intro + capabilities + approach + relatedProjects(related) + relatedServices(connected) + globalCTA({ kicker: `Capability / ${service.number}`, title: `Need ${service.title.toLowerCase()} for a <em>real project?</em>`, text: "Build the scope around the asset, launch stage and channels that matter.", button: "Start the conversation" }) });
}

export function workIndexPage() {
  const hero = pageHero({ kicker: "Selected work", title: "Real projects. <em>Integrated launches.</em>", summary: "A selection of real estate plans and auctions where Grenada delivered combinations of branding, campaign systems, landing pages, printed materials, media, outdoor and event execution.", breadcrumbItems: [{ label: "Work", href: "/work/" }], visual: `<div class="page-media-frame"><img src="/assets/shorfat.webp" alt="Grenada Studio selected real estate campaign work" width="1319" height="791" fetchpriority="high"><span>Selected work / KSA</span></div>`, modifier: "work-index-hero" });
  const grid = `<section class="section"><div class="shell">${sectionHead("Case studies", "The work, organized by project.", "Each case study uses one shared template. Project metadata and scope live separately, so template changes propagate across the archive.")}<div class="template-project-grid template-project-grid--archive">${projects.map(projectCard).join("")}</div></div></section>`;
  const field = `<section class="section"><div class="shell"><div class="showcase"><div class="showcase-card" data-reveal><img src="/assets/photos/production.webp" srcset="/assets/photos/production-m.webp 960w, /assets/photos/production.webp 2200w" sizes="(max-width: 820px) 100vw, 50vw" alt="Camera operator filming on location" width="2200" height="1467" loading="lazy"><div class="caption"><b>On-ground execution</b><span>Venue coverage, live events, production and physical campaign touchpoints.</span></div></div><div class="showcase-card" data-reveal><img src="/assets/photos/film-set.webp" srcset="/assets/photos/film-set-m.webp 960w, /assets/photos/film-set.webp 2200w" sizes="(max-width: 820px) 100vw, 50vw" alt="Studio set lit for a content shoot" width="2200" height="1467" loading="lazy"><div class="caption"><b>Creator & influencer marketing</b><span>Campaign ideas, scripts, creator coordination and content built to extend project reach.</span></div></div></div></div></section>`;
  return documentLayout({ title: "Work", description: "Selected Grenada Studio real estate marketing projects and auction campaign case studies.", active: "work", path: "/work/", content: hero + grid + field + globalCTA({ kicker: "Next case study", title: "Make the next launch <em>worth showing.</em>", text: "Bring Grenada in early enough to connect the story, campaign system and execution.", button: "Discuss a project" }) });
}

export function caseStudyPage(slug) {
  const project = getProject(slug);
  if (!project) return null;
  const connected = project.serviceSlugs.map(getService).filter(Boolean);
  const idx = projects.findIndex((item) => item.slug === slug);
  const next = projects[(idx + 1) % projects.length];
  const overview = `<section class="section case-overview"><div class="shell"><div class="case-overview-grid"><div class="case-overview-label kicker" data-reveal>Recorded scope</div><div class="case-overview-copy" data-reveal><h2>${project.title} brought multiple campaign disciplines into one real estate launch.</h2><p>Grenada ran the campaign for <strong>${project.title}</strong>${project.titleAr ? ` (<span lang="ar">${project.titleAr}</span>)` : ""} in ${project.location} (${project.type}). The scope below lists what was delivered, taken from the project files.</p></div></div><div class="case-scope">${project.services.map((item, i) => `<div class="case-scope-item" data-reveal><span>${String(i+1).padStart(2,"0")}</span><strong>${item}</strong></div>`).join("")}</div></div></section>`;
  const facts = project.facts ? `<section class="case-facts"><div class="shell"><dl class="case-facts-grid">${project.facts.map(([v, k]) => `<div data-reveal><dt>${v}</dt><dd>${k}</dd></div>`).join("")}</dl></div></section>` : "";
  const gallery = project.gallery?.length ? `<section class="section case-gallery"><div class="shell">${sectionHead("From the campaign", "Shot, designed and installed by Grenada.", "Selected frames from the project's photography, renders and live placements.")}<div class="case-gallery-grid">${project.gallery.map(([name, alt]) => `<figure data-reveal><img src="/assets/work/${name}.webp" srcset="/assets/work/${name}-m.webp 960w, /assets/work/${name}.webp 2000w" sizes="(max-width: 820px) 100vw, 50vw" alt="${alt}" width="1600" height="900" loading="lazy" decoding="async"></figure>`).join("")}</div></div></section>` : "";
  const systems = `<section class="section case-system"><div class="shell">${sectionHead("Connected disciplines", "One project, multiple touchpoints.", "The case study template maps the recorded scope back to Grenada’s reusable service system.")}<div class="template-service-grid">${connected.map(serviceCard).join("")}</div></div></section>`;
  const nextProject = `<section class="next-project"><a href="/work/${next.slug}/" class="shell next-project-link" data-reveal><span class="kicker">Next project</span><div><h2>${next.title}</h2><p>${next.location} · ${next.type}</p></div><b aria-hidden="true">↗</b></a></section>`;
  return documentLayout({ title: project.title, description: `${project.title} — ${project.type} in ${project.location}. Selected campaign work by Grenada Studio.`, active: "work", path: `/work/${project.slug}/`, bodyClass: "case-page", content: caseHero(project) + facts + overview + gallery + systems + globalCTA({ kicker: "Build the next case study", title: "Your project can use the same <em>integrated model.</em>", text: "Define the right mix of strategy, creative, media, web, production and field execution around the asset.", button: "Discuss your project" }) + nextProject });
}

export function approachPage() {
  const hero = pageHero({ kicker: "How we work", title: "Strategy to execution, <em>without the handoff gap.</em>", summary: "Grenada connects current digital marketing thinking with fully integrated field solutions, so the project story can stay coherent from positioning through measurement.", breadcrumbItems: [{ label: "Approach", href: "/approach/" }], modifier: "approach-hero" });
  const steps = [
    ["01", "Position", "Define the market story.", "Audience, offer, competitive context, message hierarchy and the narrative the project needs to own."],
    ["02", "Build", "Create the campaign system.", "Identity, content, landing experiences, media assets, outdoor and sales-support material."],
    ["03", "Launch", "Activate every channel.", "Paid media, social publishing, creators, on-ground execution, event coverage and lead capture."],
    ["04", "Optimize", "Measure and improve.", "CRO, KPIs, ROI, analytics, reporting and continuous refinement across the campaign lifecycle."]
  ];
  const process = `<section class="section approach-flow"><div class="shell">${sectionHead("Operating model", "4 stages. One connected team.", "The sequence is simple on purpose. Complexity belongs inside the execution, not inside the client experience.")}<div class="approach-stack">${steps.map(([n,label,title,copy])=>`<article class="approach-row" data-reveal><span>${n}</span><div class="kicker">${label}</div><h3>${title}</h3><p>${copy}</p></article>`).join("")}</div></div></section>`;
  const principle = `<section class="template-statement"><div class="shell"><div class="statement-grid"><div class="kicker" data-reveal>The principle</div><h2 data-reveal>Every discipline should know what the project is trying to <em>move.</em></h2><p data-reveal>That shared commercial context is what lets design, content, media, web and production behave like one campaign instead of parallel deliverables.</p></div></div></section>`;
  return documentLayout({ title: "Approach", description: "Grenada Studio’s integrated real estate marketing process: position, build, launch and optimize.", active: "approach", path: "/approach/", content: hero + process + principle + globalCTA({ kicker: "Start at stage one", title: "Bring us in before the <em>handoffs begin.</em>", text: "The earlier the positioning, creative and execution teams share context, the stronger the campaign system can become.", button: "Start a project" }) });
}

export function contactPage() {
  const hero = pageHero({ kicker: "Contact Grenada", title: "Let’s build something that <em>moves.</em>", summary: "Tell us what you are launching, where it is, and what stage the project is in. We can shape the right mix of strategy, creative, media, web, production and field execution.", breadcrumbItems: [{ label: "Contact", href: "/contact/" }], modifier: "contact-page-hero" });
  const contact = `<section class="section contact-page-section"><div class="shell"><div class="contact-layout"><aside class="contact-panel" data-reveal><div class="kicker">Direct contact</div><h2>${site.email}</h2><dl><div><dt>Studio</dt><dd>${site.address}</dd></div><div><dt>Focus</dt><dd>${site.focus}</dd></div><div><dt>LinkedIn</dt><dd><a href="${site.social.linkedin}" target="_blank" rel="noopener">Grenada Studio ↗</a></dd></div></dl></aside><form class="contact-form" data-mailto-form data-reveal="right"><div class="form-grid"><label><span>Name</span><input name="name" type="text" autocomplete="name" placeholder="Your name…" required></label><label><span>Company</span><input name="company" type="text" autocomplete="organization" placeholder="Company or project…"></label><label><span>Email</span><input name="email" type="email" autocomplete="email" spellcheck="false" placeholder="name@company.com…" required></label><label><span>Phone</span><input name="phone" type="tel" autocomplete="tel" inputmode="tel" placeholder="+20 / +966 …"></label><label class="form-wide"><span>Project type</span><select name="projectType"><option>Real estate project</option><option>Auction campaign</option><option>Brand identity</option><option>Performance marketing</option><option>Media production</option><option>Website / landing page</option><option>Integrated scope</option></select></label><label class="form-wide"><span>Project details</span><textarea name="details" rows="7" placeholder="Location, launch timing, asset type and what you need help with…" required></textarea></label></div><button class="btn btn-primary" type="submit">Prepare email <svg aria-hidden="true" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M5 12h14M13 6l6 6-6 6"/></svg></button><p class="form-note">This opens your email app with the project details prepared for ${site.email}.</p></form></div></div></section>`;
  return documentLayout({ title: "Contact", description: "Contact Grenada Studio about a real estate marketing, auction, branding, performance, web or media production project.", active: "contact", path: "/contact/", bodyClass: "contact-page", content: hero + contact });
}

export function notFoundPage() {
  const content = `<section class="page-hero error-hero" id="top"><div class="shell"><div class="error-code" aria-hidden="true">404</div><div class="page-hero-copy"><div class="kicker">Page not found</div><h1>This route moved out of the <em>campaign.</em></h1><p>The page you requested does not exist. Return to Grenada Studio or browse the work.</p><div class="hero-actions"><a class="btn btn-primary" href="/">Back home</a><a class="btn btn-ghost" href="/work/">View work</a></div></div></div></section>`;
  return documentLayout({ title: "Page not found", description: "The requested Grenada Studio page was not found.", path: "/404.html", content });
}
