import { documentLayout } from "./layouts.mjs";
import { services } from "./data/services.mjs";
import { getProject } from "./data/projects.mjs";

export function parallaxHomePage() {
  const featured = ["shorfat-al-haram", "malqa-taif", "dream-land"].map(getProject).filter(Boolean);
  const storyFrames = [
    { n: "01", label: "Position", title: "Define the market story.", copy: "Audience, offer, competitive context and message hierarchy become one position the project can own.", image: "/assets/hero-office.webp", alt: "Grenada Studio creative office during campaign planning" },
    { n: "02", label: "Build", title: "Create the campaign system.", copy: "Identity, content, landing experiences, outdoor and sales-support material are developed as one visual and verbal language.", image: "/assets/malqa.webp", alt: "Malqa Taif real estate campaign identity and marketing materials" },
    { n: "03", label: "Launch", title: "Activate every channel.", copy: "Paid media, social publishing, creators, field execution and event coverage move together instead of as separate handoffs.", image: "/assets/event-coverage.webp", alt: "Grenada Studio on-ground event and auction campaign execution" },
    { n: "04", label: "Optimize", title: "Measure what moves.", copy: "CRO, KPIs, ROI and reporting feed the next creative and media decision while the campaign is still live.", image: "/assets/shorfat.webp", alt: "Shorfat Al Haram integrated real estate campaign work" }
  ];
  const hero = `<section class="px-hero" id="top" data-px-hero>
    <div class="px-progress" aria-hidden="true"><span></span></div>
    <div class="px-hero-media" aria-hidden="true"><div class="px-hero-image"><img src="/assets/hero-office.webp" alt="" width="1319" height="791" fetchpriority="high"></div><div class="px-hero-shade"></div><div class="px-hero-gridfx"></div></div>
    <div class="shell px-hero-shell">
      <div class="px-hero-top"><span class="kicker">Home study 02 / Scroll narrative</span><a href="/" class="px-switch" data-snd>View current home <span aria-hidden="true">↗</span></a></div>
      <div class="px-hero-copy"><p class="px-overline">Integrated real estate marketing · KSA & Egypt</p><h1>We build <em>demand</em><br>for real estate.</h1><p class="px-hero-desc">Strategy, creative, performance and field execution arranged as one market-moving system.</p></div>
      <div class="px-hero-foot"><span>Scroll to enter the system</span><span class="px-scroll-mark" aria-hidden="true"><i></i></span><span>Grenada Studio / 2026</span></div>
    </div>
  </section>`;

  const manifesto = `<section class="px-manifesto" aria-labelledby="px-manifesto-title"><div class="shell"><div class="px-manifesto-grid"><div class="kicker">The difference</div><h2 id="px-manifesto-title"><span class="px-word">Digital thinking.</span><span class="px-word">Field execution.</span><span class="px-word px-word-accent">One campaign system.</span></h2><p>Real estate does not move through one channel. Grenada connects the story, the media, the experience and the field execution around the same commercial objective.</p></div></div></section>`;

  const story = `<section class="px-story" id="px-story" aria-labelledby="px-story-title"><div class="shell"><div class="px-story-head"><div><div class="kicker">How demand is built</div><h2 id="px-story-title">Four stages.<br><em>One continuous system.</em></h2></div><p>Scroll through the operating model. Each stage changes the same campaign, rather than handing the project to a new supplier.</p></div><div class="px-story-stage"><div class="px-story-copy">${storyFrames.map((item,i)=>`<article class="px-story-step${i===0?' is-first':''}" data-step="${i}"><span>${item.n}</span><div><div class="kicker">${item.label}</div><h3>${item.title}</h3><p>${item.copy}</p></div></article>`).join("")}</div><div class="px-story-visual" aria-label="Grenada campaign stages">${storyFrames.map((item,i)=>`<figure class="px-story-frame${i===0?' is-first':''}" data-frame="${i}"><img src="${item.image}" alt="${item.alt}" width="1319" height="791" ${i===0?'':'loading="lazy"'}><figcaption><span>${item.n} / ${item.label}</span><b>${item.title}</b></figcaption></figure>`).join("")}<div class="px-story-counter" aria-hidden="true"><span>01</span><i></i><b>04</b></div></div></div></div></section>`;

  const projectsSection = `<section class="px-work" aria-labelledby="px-work-title"><div class="shell px-work-intro"><div class="kicker">Selected work</div><h2 id="px-work-title">Proof lives in the <em>launch.</em></h2><p>Three projects, each treated as a full-screen editorial scene rather than a card grid.</p></div>${featured.map((project,i)=>`<article class="px-project" data-project-scene><a href="/work/${project.slug}/" class="shell px-project-link"><div class="px-project-media"><img src="${project.image}" alt="${project.alt}" width="1319" height="791" loading="lazy"><span class="px-project-number" aria-hidden="true">0${i+1}</span></div><div class="px-project-info"><div><span class="kicker">${project.location} / Selected case study</span><h3>${project.title}</h3></div><div><p>${project.type}</p><p class="px-project-services">${project.services.slice(0,5).join(" · ")}</p><span class="px-project-arrow">View case study ↗</span></div></div></a></article>`).join("")}</section>`;

  const convergence = `<section class="px-convergence" aria-labelledby="px-convergence-title"><div class="shell"><div class="px-convergence-head"><div class="kicker">Field × digital</div><h2 id="px-convergence-title">Different surfaces.<br><em>One campaign.</em></h2></div><div class="px-convergence-stage"><figure class="px-plane px-plane-field"><img src="/assets/event-coverage.webp" alt="Grenada on-ground auction event coverage" width="1319" height="791" loading="lazy"><figcaption>FIELD / Physical attention</figcaption></figure><div class="px-convergence-word" aria-hidden="true"><span>ONE</span><b>CAMPAIGN</b></div><figure class="px-plane px-plane-digital"><img src="/assets/influencer-marketing.webp" alt="Influencer and creator marketing campaign by Grenada Studio" width="1319" height="791" loading="lazy"><figcaption>DIGITAL / Distributed attention</figcaption></figure></div><p class="px-convergence-copy">The brand should feel like the same project whether someone meets it on a phone, a roadside billboard, a sales deck or the auction floor.</p></div></section>`;

  const capabilityField = `<section class="px-capabilities" aria-labelledby="px-capabilities-title"><div class="shell"><div class="px-capabilities-head"><div class="kicker">10 connected capabilities</div><h2 id="px-capabilities-title">A service list should feel like a <em>system.</em></h2></div><div class="px-capability-field">${services.map((service,i)=>`<a class="px-capability" data-depth="${(i%4)+1}" href="/services/${service.slug}/"><span>${service.number}</span>${service.title}<i aria-hidden="true">↗</i></a>`).join("")}</div></div></section>`;

  const proof = `<section class="px-proof" aria-label="Grenada operating proof"><div class="shell"><div class="px-proof-row"><div class="px-proof-num" data-px-proof>360°</div><div><span class="kicker">Integrated execution</span><p>Digital, creative, production and field touchpoints connected around one launch.</p></div></div><div class="px-proof-row"><div class="px-proof-num" data-px-proof>10</div><div><span class="kicker">Core capabilities</span><p>Specialists can enter independently, while the project still keeps one campaign language.</p></div></div><div class="px-proof-row"><div class="px-proof-num px-proof-words" data-px-proof>Digital<br><em>+</em> Field</div><div><span class="kicker">One operating model</span><p>What happens online and what happens on the ground are treated as one customer journey.</p></div></div></div></section>`;

  const partners = `<section class="px-partners" aria-labelledby="px-partners-title"><div class="shell"><div class="px-partners-media"><img src="/assets/partners.webp" alt="Selection of organizations and partners that worked with Grenada Studio" width="1319" height="791" loading="lazy"></div><div class="px-partners-copy"><div class="kicker">Trusted partnerships</div><h2 id="px-partners-title">Chosen by teams with <em>serious assets at stake.</em></h2><p>Major launches and auction campaigns demand more than visual polish. They need a team that can stay coherent across channels, timelines and physical execution.</p></div></div></section>`;

  const closing = `<section class="px-closing"><div class="shell"><div class="px-closing-line"></div><div class="px-closing-grid"><div class="kicker">Ready when the asset is</div><div><h2>Move the market.<br><em>Not just the feed.</em></h2><p>Bring Grenada in early enough to shape the position, creative system and launch mechanics together.</p><div class="px-closing-actions"><a class="btn btn-primary" href="/contact/" data-snd>Start a project <span aria-hidden="true">↗</span></a><a class="btn btn-ghost" href="/work/" data-snd>Explore the work</a></div></div></div></div></section>`;

  return documentLayout({
    title: "Parallax Home Study",
    description: "Experimental cinematic homepage study for Grenada Studio using scroll-linked parallax storytelling.",
    path: "/home-parallax/",
    bodyClass: "parallax-page",
    content: hero + manifesto + story + projectsSection + convergence + capabilityField + proof + partners + closing,
    extraHead: `<meta name="robots" content="noindex,nofollow" /><link rel="preload" as="image" href="/assets/hero-office.webp" /><link rel="stylesheet" href="/assets/parallax.css" />`,
    extraScripts: `<script src="https://cdn.jsdelivr.net/npm/gsap@3.13.0/dist/gsap.min.js" defer></script><script src="https://cdn.jsdelivr.net/npm/gsap@3.13.0/dist/ScrollTrigger.min.js" defer></script><script src="/assets/parallax.js" defer></script>`
  });
}
